### PR TITLE
Update Polish (pl) localization

### PR DESCRIPTION
**Pull request by piotrdrag**
needs-review: @splewako

### CODE REVIEW

**Comment by splewako** [comment]
Looks good. I would translate promote_firefox_hello_heading2 as "Pobierz {{brandShortname}} i zacznij dzielić się stronami." but that could be my personal preference.

**Comment by piotrdrag** [comment]
I like it - I've changed it to your version.

**Comment by Standard8** [comment]
@splewako is this ready to merge now?

**Comment by splewako** [comment]
@Standard8: yes

**Pull request merged**
