### PR TITLE
Update Polish (pl) localization

### PR DESCRIPTION
**Pull request by splewako**

### CODE REVIEW

**Comment by splewako** [comment]
@Mardak: do you know by accident who should be pinged about this repository issues and pull requests?

**Comment by Mardak** [comment]
Are you asking who should be able to review/land your pull request? @flodolo or @Standard8 might know. I'll check on IRC.

**Comment by Mardak** [comment]
Standard8 says @mathjazz might know the l10n pull request process better.

**Comment by mathjazz** [comment]
@Mardak The Polish community prefers to work with repositories directly instead of using our tools, which have permission system built it. So somebody will have to land their PRs.

So anything you get from @splewako and looks technically ok can be merged. ;)

**Comment by splewako** [comment]
Thank you!

**Pull request merged**
