### PR TITLE
Update l10n/pl/loop.properties

### PR DESCRIPTION
**Pull request by splewako**
Update pl to better match https://hg.mozilla.org/l10n-central/pl/annotate/tip/browser/chrome/browser/loop/loop.properties and few other fixes.

### CODE REVIEW

**Comment by splewako** [comment]
@Standard8 - could you help with merging this pr (or mention someone who can)?

**Comment by splewako** [comment]
@mathjazz - could you help with merging this pr (or mention someone who can)?

**Comment by mathjazz** [comment]
Hi @splewako, there is an ongoing pl effort in Verbatim:
https://localize.mozilla.org/pl/loop/

Could you upload translations there, so other localizers will be aware of this?

**Comment by splewako** [comment]
> Hi @splewako, there is an ongoing pl effort in Verbatim:
> https://localize.mozilla.org/pl/loop/
> Could you upload translations there, so other localizers will be aware of this?

No, sorry, I'm not interested in working on Verbatim and other localizers should be aware already.
Also, please remove that project from Verbatim if you can.

**Comment by mathjazz** [comment]
OK, there's no need to submit translations through Verbatim (or Pontoon) if you prefer to work directly on files (GitHub in this case).

But the projects needs to stay in Verbatim, because we update files against templates through Verbatim for this particular project.

**Comment by splewako** [comment]
> OK, there's no need to submit translations through Verbatim (or Pontoon) if you prefer to work directly on files (GitHub in this case).

Yes, in general we prefer to work with VCS.

> But the projects needs to stay in Verbatim, because we update files against templates through Verbatim for this particular project.

That shouldn't be big problem if pull requests will be reasonably handled.

**Comment by mathjazz** [comment]
That's true, but you will need to take care of merges on your own.

Please let me know if that's fine with you and your team is aware we'll remove the project from Verbatim..

**Comment by splewako** [comment]
> That's true, but you will need to take care of merges on your own

Probably doable but I'm not exactly sure what do you mean by that. (adding strings to localized file?)

I was trying to say that, if someone will act on pull requests in reasonable time (not after months) then I don't see a problem in project existing on Verbatim.

**Comment by mathjazz** [comment]
Oh, sorry, I didn't get that right. 

OK, so we're keeping the project in Verbatim and I hope someone will merge this finally. I don't have access, but if you upload changes to Verbatim, I can commit immediately.

**Comment by splewako** [comment]
@flodolo - could you help with merging this pr (or mention someone who can)?

**Comment by flodolo** [comment]
I don't have any rights on these repos, your best luck is to ping someone in #loop on IRC.

We already had this discussion in the past:
- Most products don't manage PRs for localization, and I think it's good for l10n. Anyone could pass by, translate the product in crappy Polish, and developers wouldn't know who owns what for that locale. Pull requests simply don't scale for l10n.
- An easy way out is to use Verbatim just to import the files you translate offline, and commit. That's a few clicks in Verbatim, you wouldn't translate anything there.

**Comment by Standard8** [comment]
Sorry, I don't always watch this repo due to the large amount of commits. As Flod says, I think we should try and use the verbatim route going forward.

I can merge this for now.

**Comment by splewako** [comment]
> As Flod says, I think we should try and use the verbatim route going forward.

Unfortunately Verbatim alone (or Pootle for that matter) without working vcs rw access for l10n doesn't work for pl.

> I can merge this for now.

Thanks!

**Pull request merged**
